credentials:
  username: <ENTER YOUR USERNAME TO ACCESS OPENSEARCH DOMAIN>
  password: <ENTER YOUR PASSWORD TO ACCESS OPENSEARCH DOMAIN>
domain:
  endpoint: <ENTER YOUR HTTPS OPENSEARCH URL HERE>
  index: <ENTER NAME OF THE INDEX YOU CREATED>
